### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by expected-ingot** [TheScienceElf/TiBASIC-Raytracing#1]
Could you please provide source code for this?

**Comment by loom4k** [comment]
I believe you should be able to edit the `.8xp` files using the TI-Connect software and the built-in file editor in that program. You can also edit the program directly on the calculator but that's not really the most efficient thing.

**Comment by Tyopo131** [comment]
> Could you please provide source code for this?

Agreed, it would be pretty cool to see the actual source code for this

**Comment by crapbass** [comment]
> > Could you please provide source code for this?
> 
> Agreed, it would be pretty cool to see the actual source code for this

Hello! I managed to install the TI Connect CE program. Here is the source code:

RAYTRSPR
```
ClrDraw:1→G
{12,24,23,22,21,20}→L₁

For(Y,0,162,2G)
(81-Y)/164→B
For(X,0,262,2G)
(X-131)/164→A

A²+B²+1→E:­2B-12→F
34.75→H:F²-4EH→D

­1/B→T

AT→U:T→V
remainder(abs(int(U)+int(V)),2)→C

12→L:12→M
12-(T>0)(C+1)→C

If D≥0:Then
(­F-√(D))/(2E)→T
AT→I:BT-1→J:6-T→K
J/1.5→M

If M>0:Then
int(10M)→M
L₁(1+int(M/2))→L
L₁(1+int(M/2+.5))→M
Else:12→M
End

{I,J,K}/1.5→L₃
{A,B,1}→L₂
2sum(L₃L₂)→S

SL₃-L₂→L₄
L₄(1)→P:L₄(2)→Q:L₄(3)→R

­(J+2)/Q→T

If T>0:Then
PT+I→U:RT+6-K→V
11-remainder(abs(int(U)+int(V)),2)→C
Else:12→C:End

Else:If T>0:Then
1→E:­4→F
U²+V²-12V+37.75→H
F²-4EH→D

12(D≥0)+C(D<0)→L
L→M
End:End

Pxl-On(Y,X,C)
Pxl-On(Y+1,X,L)
Pxl-On(Y,X+1,M)
Pxl-On(Y+1,X+1,C)
End:End
```

RAYTRMAX
```
1→G
{12,24,23,22,21,20}→L₁

For(O,1,­1,­1)
For(N,­1,1)

ClrDraw
For(Y,0,162,2G)
(81-Y+164O)/164/3→B
For(X,0,262,2G)
(X-131+264N)/164/3→A

A²+B²+1→E:­2B-12→F
34.75→H:F²-4EH→D

­1/B→T

AT→U:T→V
remainder(abs(int(U)+int(V)),2)→C

12→L:12→M
12-(T>0)(C+1)→C

If D≥0:Then
(­F-√(D))/(2E)→T
AT→I:BT-1→J:6-T→K
J/1.5→M

If M>0:Then
int(10M)→M
L₁(1+int(M/2))→L
L₁(1+int(M/2+.5))→M
Else:12→M
End

{I,J,K}/1.5→L₃
{A,B,1}→L₂
2sum(L₃L₂)→S

SL₃-L₂→L₄
L₄(1)→P:L₄(2)→Q:L₄(3)→R

­(J+2)/Q→T

If T>0:Then
PT+I→U:RT+6-K→V
11-remainder(abs(int(U)+int(V)),2)→C
Else:12→C:End

Else:If T>0:Then
1→E:­4→F
U²+V²-12V+37.75→H
F²-4EH→D

12(D≥0)+C(D<0)→L
L→M
End:End

Pxl-On(Y,X,C)
Pxl-On(Y+1,X,L)
Pxl-On(Y,X+1,M)
Pxl-On(Y+1,X+1,C)
End:End
3(O+1)+(N+1)→I
prgmRECORD
End:End
```

RECORD
```
If I=0:StorePic Pic1
If I=1:StorePic Pic2
If I=2:StorePic Pic3
If I=3:StorePic Pic4
If I=4:StorePic Pic5
If I=5:StorePic Pic6
If I=6:StorePic Pic7
If I=7:StorePic Pic8
If I=8:StorePic Pic9
If I=9:StorePic Pic0
```

PANOVIEW
```
RecallPic Pic5
1→X:1→Y

While 1
0→K
While (K<24 or K>26)(K≠34):getKey→K:End
X+(K=26)-(K=24)→X
Y+(K=25)-(K=34)→Y
X(X≥0 and X≤2)+2(X>2)→X
Y(Y≥0 and Y≤2)+2(Y>2)→Y
3Y+X→F
If F=0:RecallPic Pic1
If F=1:RecallPic Pic2
If F=2:RecallPic Pic3
If F=3:RecallPic Pic4
If F=4:RecallPic Pic5
If F=5:RecallPic Pic6
If F=6:RecallPic Pic7
If F=7:RecallPic Pic8
If F=8:RecallPic Pic9
End
```

**Comment by Tyopo131** [comment]
> > > Could you please provide source code for this?
> > 
> > 
> > Agreed, it would be pretty cool to see the actual source code for this
> 
> Hello! I managed to install the TI Connect CE program. Here is the source code:
> 
> RAYTRSPR
> 
> ```
> ClrDraw:1→G
> {12,24,23,22,21,20}→L₁
> 
> For(Y,0,162,2G)
> (81-Y)/164→B
> For(X,0,262,2G)
> (X-131)/164→A
> 
> A²+B²+1→E:­2B-12→F
> 34.75→H:F²-4EH→D
> 
> ­1/B→T
> 
> AT→U:T→V
> remainder(abs(int(U)+int(V)),2)→C
> 
> 12→L:12→M
> 12-(T>0)(C+1)→C
> 
> If D≥0:Then
> (­F-√(D))/(2E)→T
> AT→I:BT-1→J:6-T→K
> J/1.5→M
> 
> If M>0:Then
> int(10M)→M
> L₁(1+int(M/2))→L
> L₁(1+int(M/2+.5))→M
> Else:12→M
> End
> 
> {I,J,K}/1.5→L₃
> {A,B,1}→L₂
> 2sum(L₃L₂)→S
> 
> SL₃-L₂→L₄
> L₄(1)→P:L₄(2)→Q:L₄(3)→R
> 
> ­(J+2)/Q→T
> 
> If T>0:Then
> PT+I→U:RT+6-K→V
> 11-remainder(abs(int(U)+int(V)),2)→C
> Else:12→C:End
> 
> Else:If T>0:Then
> 1→E:­4→F
> U²+V²-12V+37.75→H
> F²-4EH→D
> 
> 12(D≥0)+C(D<0)→L
> L→M
> End:End
> 
> Pxl-On(Y,X,C)
> Pxl-On(Y+1,X,L)
> Pxl-On(Y,X+1,M)
> Pxl-On(Y+1,X+1,C)
> End:End
> ```
> 
> RAYTRMAX
> 
> ```
> 1→G
> {12,24,23,22,21,20}→L₁
> 
> For(O,1,­1,­1)
> For(N,­1,1)
> 
> ClrDraw
> For(Y,0,162,2G)
> (81-Y+164O)/164/3→B
> For(X,0,262,2G)
> (X-131+264N)/164/3→A
> 
> A²+B²+1→E:­2B-12→F
> 34.75→H:F²-4EH→D
> 
> ­1/B→T
> 
> AT→U:T→V
> remainder(abs(int(U)+int(V)),2)→C
> 
> 12→L:12→M
> 12-(T>0)(C+1)→C
> 
> If D≥0:Then
> (­F-√(D))/(2E)→T
> AT→I:BT-1→J:6-T→K
> J/1.5→M
> 
> If M>0:Then
> int(10M)→M
> L₁(1+int(M/2))→L
> L₁(1+int(M/2+.5))→M
> Else:12→M
> End
> 
> {I,J,K}/1.5→L₃
> {A,B,1}→L₂
> 2sum(L₃L₂)→S
> 
> SL₃-L₂→L₄
> L₄(1)→P:L₄(2)→Q:L₄(3)→R
> 
> ­(J+2)/Q→T
> 
> If T>0:Then
> PT+I→U:RT+6-K→V
> 11-remainder(abs(int(U)+int(V)),2)→C
> Else:12→C:End
> 
> Else:If T>0:Then
> 1→E:­4→F
> U²+V²-12V+37.75→H
> F²-4EH→D
> 
> 12(D≥0)+C(D<0)→L
> L→M
> End:End
> 
> Pxl-On(Y,X,C)
> Pxl-On(Y+1,X,L)
> Pxl-On(Y,X+1,M)
> Pxl-On(Y+1,X+1,C)
> End:End
> 3(O+1)+(N+1)→I
> prgmRECORD
> End:End
> ```
> 
> RECORD
> 
> ```
> If I=0:StorePic Pic1
> If I=1:StorePic Pic2
> If I=2:StorePic Pic3
> If I=3:StorePic Pic4
> If I=4:StorePic Pic5
> If I=5:StorePic Pic6
> If I=6:StorePic Pic7
> If I=7:StorePic Pic8
> If I=8:StorePic Pic9
> If I=9:StorePic Pic0
> ```
> 
> PANOVIEW
> 
> ```
> RecallPic Pic5
> 1→X:1→Y
> 
> While 1
> 0→K
> While (K<24 or K>26)(K≠34):getKey→K:End
> X+(K=26)-(K=24)→X
> Y+(K=25)-(K=34)→Y
> X(X≥0 and X≤2)+2(X>2)→X
> Y(Y≥0 and Y≤2)+2(Y>2)→Y
> 3Y+X→F
> If F=0:RecallPic Pic1
> If F=1:RecallPic Pic2
> If F=2:RecallPic Pic3
> If F=3:RecallPic Pic4
> If F=4:RecallPic Pic5
> If F=5:RecallPic Pic6
> If F=6:RecallPic Pic7
> If F=7:RecallPic Pic8
> If F=8:RecallPic Pic9
> End
> ```

Cool thanks!
